language: objective-c
osx_image: xcode8.3
env:
  - DESTINATION="OS=10.2,name=iPhone 7" SCHEME="SwiftyOnboardVC" SDK=iphonesimulator
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project SwiftyOnboardVC.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c